# It's presumed that you have libxml2 installed in the standard location
# with include files in /usr/include/libxml2. If it lives elsewhere you will
# have to adjust the path below accordingly.
#
autoLoader_EXTRA_INCLUDES = -I/usr/include/libxml2
