#ifndef _MFnImageSource
#define _MFnImageSource
//-
// ==========================================================================
// Copyright (C) 2010 Autodesk, Inc., and/or its licensors.  All
// rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its
// licensors,  which is protected by U.S. and Canadian federal copyright law
// and by international treaties.
//
// The Data may not be disclosed or distributed to third parties or be
// copied or duplicated, in whole or in part, without the prior written
// consent of Autodesk.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the following
// disclaimer, must be included in all copies of the Software, in whole
// or in part, and all derivative works of the Software, unless such copies
// or derivative works are solely in the form of machine-executable object
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// AUTODESK DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO
// EVENT WILL AUTODESK AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR
// CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS LICENSORS HAS
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
// ==========================================================================
//+
//
// CLASS:    MFnImageSource
//
// ****************************************************************************

#if defined __cplusplus

// ****************************************************************************
// INCLUDED HEADER FILES


#include <maya/MStatus.h>
#include <maya/MString.h>
#include <maya/MTypes.h>
#include <maya/MFnDependencyNode.h>
// Unfortunate include for MCommonRenderSettingsData::MpathType
#include <maya/MCommonRenderSettingsData.h>

// ****************************************************************************
// DECLARATIONS

class MObject;

// ****************************************************************************
// CLASS DECLARATION (MFnImageSource)

//! \ingroup OpenMayaRender MFn
//! \brief Function set for image sources.
/*!
An image source is a node that is used in render graphs, e.g. compositing 
graphs, shading  networks.  It provides access to the images produced by 3D 
scene renderers, or 2D image processing tasks.  This class provides 
functionality for working with image sources, e.g. retrieving the path of
rendered image source files.
*/

class OPENMAYARENDER_EXPORT MFnImageSource : public MFnDependencyNode
{
	declareMFn(MFnImageSource, MFnDependencyNode);

public:

 	MString	getImageName(
           MCommonRenderSettingsData::MpathType pathType,
           double                               frameNumber,
           const MString&                       sceneName,
           const MObject                        camera,
           const MObject                        renderLayer,
           MString*                             bufferName = NULL,
           MStatus*                             ReturnStatus = NULL
        ) const;   

    MObject sourceLayer(const MObject& currentLayer, MStatus* ReturnStatus = NULL);

    MObject sourceCamera(const MObject& currentCamera, MStatus* ReturnStatus = NULL);

BEGIN_NO_SCRIPT_SUPPORT:

 	declareMFnConstConstructor( MFnImageSource, MFnDependencyNode );

END_NO_SCRIPT_SUPPORT:

};

#endif /* __cplusplus */
#endif /* _MFnImageSource */
