#ifndef _MFnNObjectData
#define _MFnNObjectData
//-
// ==========================================================================
// Copyright (C) 2008 - 2010 Autodesk, Inc., and/or its licensors.  All 
// rights reserved.
// 
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished 
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its 
// licensors,  which is protected by U.S. and Canadian federal copyright law 
// and by international treaties.
// 
// The Data may not be disclosed or distributed to third parties or be 
// copied or duplicated, in whole or in part, without the prior written 
// consent of Autodesk.
// 
// The copyright notices in the Software and this entire statement, 
// including the above license grant, this restriction and the following 
// disclaimer, must be included in all copies of the Software, in whole 
// or in part, and all derivative works of the Software, unless such copies 
// or derivative works are solely in the form of machine-executable object 
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
// AUTODESK DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED 
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF 
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO 
// EVENT WILL AUTODESK AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST 
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR 
// CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS LICENSORS HAS 
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES. 
// ==========================================================================
//+
//
// CLASS:    MFnNObjectData
//
// ****************************************************************************

#if defined __cplusplus

// ****************************************************************************
// INCLUDED HEADER FILES


#include <maya/MFnData.h>

// ****************************************************************************
// DECLARATIONS

class MPoint;
class MnCloth;
class MnRigid;
class MnParticle;

// ****************************************************************************
// CLASS DECLARATION (MFnNObjectData)

//! \ingroup OpenMayaFX MFn
//! \brief function set for nCloth object data 
/*!
  Class for transferring N object data between connections
*/
class OPENMAYAFX_EXPORT MFnNObjectData : public MFnData
{
    declareMFn( MFnNObjectData, MFnData );

public:


    MObject         create() const ;
BEGIN_NO_SCRIPT_SUPPORT:
	//!	NO SCRIPT SUPPORT
	MStatus			getObjectPtr( MnCloth *& ptr ) const;
	//!	NO SCRIPT SUPPORT
	MStatus			getObjectPtr( MnRigid *& ptr ) const;
	//!	NO SCRIPT SUPPORT
	MStatus			getObjectPtr( MnParticle *& ptr ) const;
END_NO_SCRIPT_SUPPORT:
	MnCloth *		getClothObjectPtr( MStatus *status=NULL ) const;
	MnRigid *		getRigidObjectPtr( MStatus *status=NULL ) const;
	MnParticle *	getParticleObjectPtr( MStatus *status=NULL ) const;
	MStatus			setObjectPtr( MnCloth * ptr );
	MStatus			setObjectPtr( MnRigid * ptr );
	MStatus			setObjectPtr( MnParticle * ptr );
    MStatus			getCollide( bool & ) const;
BEGIN_NO_SCRIPT_SUPPORT:
	//!	NO SCRIPT SUPPORT
    MStatus         getCached( bool & cached ) const;
END_NO_SCRIPT_SUPPORT:
	bool			isCached( MStatus *status=NULL ) const;
    MStatus         setCached( bool cached );


BEGIN_NO_SCRIPT_SUPPORT:

 	declareMFnConstConstructor( MFnNObjectData, MFnData );

END_NO_SCRIPT_SUPPORT:

protected:
// No protected members

private:
// No Private members
};

#endif /* __cplusplus */
#endif /* _MFnNObjectData */
