#ifndef __MPxClientDeviceNode_h
#define __MPxClientDeviceNode_h
//-
// ==========================================================================
// Copyright (C) 2011 Autodesk, Inc., and/or its licensors.  All
// rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its
// licensors,  which is protected by U.S. and Canadian federal copyright law
// and by international treaties.
//
// The Data may not be disclosed or distributed to third parties or be
// copied or duplicated, in whole or in part, without the prior written
// consent of Autodesk.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the following
// disclaimer, must be included in all copies of the Software, in whole
// or in part, and all derivative works of the Software, unless such copies
// or derivative works are solely in the form of machine-executable object
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// AUTODESK DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO
// EVENT WILL AUTODESK AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR
// CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS LICENSORS HAS
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
// ==========================================================================
//+
//
// CLASS:    MPxClientDeviceNode
//
// ****************************************************************************

#if defined __cplusplus

// ****************************************************************************
// INCLUDED HEADER FILES
#include <maya/MPxThreadedDeviceNode.h>
#include <maya/MTypes.h>
#include <maya/MObjectArray.h>
#include <maya/MString.h>

// Forward
class MCharBuffer;

// ****************************************************************************
// CLASS DECLARATION (MPxClientDeviceNode)

//! \ingroup OpenMayaUI MPx
//! \brief Base class for client device creation 
/*!
  MPxClientDeviceNode is an extension of MPxThreadedDevice node, and is
  intended for creating maya devices that act as clients.  An example 
  of this will be a Maya device that listens for animation data that is
  sent from another application.

  See MPxThreadedDevice node for details on how to use the memory queue system

  Plug-ins should create the MPxClientDeviceNode with a kCustomClient
  parameter.

  This class contains the serverName and deviceName attributes.  If these
  attributes are changed, the node will restart the thread so that 
  processing will continue with the new settings.

  NOTE: This class relies on the idle event queue to perform the node
  attribute updating.  As a result, it will not work in Maya batch mode.
*/

class OPENMAYAUI_EXPORT MPxClientDeviceNode : public MPxThreadedDeviceNode
{
public:
	//! Defines the type client server
	enum ClientType 
	{
		kUser,					//!< Custom client implemented in a plug-in
		kInternal,				//!< Autodesk specific
	};

	MPxClientDeviceNode( ClientType typ = kUser );

	virtual ~MPxClientDeviceNode();

	virtual MPxNode::Type type() const;

	ClientType clientType();

	// Thread handler
	virtual void threadHandler( const char* serverName, const char* deviceName );

	//
	// Attributes
	//

	//! Server
	static MObject serverName;
	//! Device
	static MObject deviceName;

	static const char *className();
private:
	MPxClientDeviceNode::ClientType clientTyp;

	static void initialSetup();
};

#endif /* _cplusplus */
#endif /* MPxClientDeviceNode */
